name: Zuri External Tools​ Plugin Pipeline
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

          # Runs a single command using the runners shell
        - name: Pull into Server
          uses: appleboy/ssh-action@master
          with:
              host: ${{ secrets.ZURI_HOST }}
              username: ${{ secrets.USERNAME }}
              password: ${{ secrets.PASSWORD }}
              script: |
                  cd /var/www/zc_plugin_tools/
                  git pull
                  cd /var/www/zc_plugin_tools/
                  npm run install
                  npm run build
                  pm2 restart external_tools_plugin
                